### ISSUE TITLE
我搞了个单列作为全局管理。发现数据有的时候会消失，大神看看呀

### ISSUE THREAD

**Issue by douya40** [mengdd/PreferencesProvider#5]
public class MyPreferencesStorageModule {
    private   static  PreferencesStorageModule preferencesStorageModele;
    public static  PreferencesStorageModule getInstance() {
        if (preferencesStorageModele == null)
            preferencesStorageModele = new PreferencesStorageModule(MyApplication.getInstance(), "HelloModule1");
        return preferencesStorageModele;
    }
}

**Comment by mengdd** [comment]
只要名字"HelloModule1"确定保持不变就可以啊.

**Comment by douya40** [comment]
是一样的，我都全局控制了

**Comment by mengdd** [comment]
@douya40 你用Stetho查看一下数据库好了.
