### ISSUE TITLE
List<String>  这种数据怎么保存

### ISSUE THREAD

**Issue by douya40** [mengdd/PreferencesProvider#6]
List<String>  这种数据怎么保存

**Comment by mengdd** [comment]
@douya40 目前没有提供直接存数组的接口. 
有一种解决思路是这样:
存的时候用一个特殊符号(比如逗号)分隔把它们拼成一个String: `Joiner.on(",").join(strings)`.
(这个是guava的方法).
然后取出来以后再把它分隔一下`s.split(",")`.
