### ISSUE TITLE
你好，新手请问能存储服务器返回的很大的json字符串吗，速度怎么样？

### ISSUE THREAD

**Issue by xiaominglei001** [mengdd/PreferencesProvider#8]
项目里以前用了sp存储了服务器返回的离线任务数据，json数据非常大，格式化后存起来有1M，用原生的sp存这个json无论是读取还是写入都很卡，应该一开始就用数据库的，可是一开始没用，现场改起来需要时间。原json比如这个：https://raw.githubusercontent.com/xiaominglei001/XiaoTest/master/README.md

**Comment by xiaominglei001** [comment]
求教！！！

**Comment by talentprince** [comment]
用realm吧

**Comment by mengdd** [comment]
@xiaominglei001 用这个库的话, 读写的形式和shared preferences类似, 底层是把数据存在数据库里的. 
你这个json数据这么大, 效率我也不知道, 你可以自己试试看. 
不论是原生的shared preferences还是我这个库初衷都是用来存储一些简短的值的.

我也不知道你存这么大的json取出来以后是怎么用的, 还是建议你们进行一下重构, 给自己设计一个数据库模块吧, 这样使用起来也方便.

**Comment by xiaominglei001** [comment]
@mengdd 感谢回复，原来从sp就是取出json后用fastjson再序列化为对象用的，确实性能很是问题，有时间是要从新用数据库实现下。
